name: Release Build

on:
  push:
    tags:
      - "v*"

jobs:
  build-macos:
    name: Build macOS
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Zig
        uses: mlugg/setup-zig@v1
        with:
          version: "0.14.0"
          use-cache: false

      - name: Setup MoonBit
        run: |
          curl -fsSL https://cli.moonbitlang.com/install/unix.sh | bash
          echo "$HOME/.moon/bin" >> $GITHUB_PATH

      - name: Build NTM Binary
        run: |
          cd ntm
          moon update
          moon build --target native
          cd ..

      - name: Prepare artifacts
        run: |
          mkdir -p dist
          cp zig-out/bin/ntm dist/ntm

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ntm-macos
          path: dist/*

  build-linux:
    name: Build Linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install build-essential
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential

      - name: Verify math.h location
        run: |
          echo "Searching for math.h..."
          ls -l /usr/include/math.h || echo "math.h not found in /usr/include"
          find /usr/include -name math.h

      - name: Setup Zig
        uses: mlugg/setup-zig@v1
        with:
          version: "0.14.0"
          use-cache: false

      - name: Setup MoonBit
        run: |
          curl -fsSL https://cli.moonbitlang.com/install/unix.sh | bash
          echo "$HOME/.moon/bin" >> $GITHUB_PATH

      - name: Build NTM Binary
        run: |
          cd ntm
          moon update
          moon build --target native
          cd ..

      - name: Prepare artifacts
        run: |
          mkdir -p dist
          cp zig-out/bin/ntm dist/ntm

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ntm-linux
          path: dist/*

  # build-windows:
  #   name: Build Windows
  #   runs-on: windows-latest
  #   steps:
  #     - uses: actions/checkout@v4
  #     - name: Setup Zig
  #       uses: mlugg/setup-zig@v1
  #       with:
  #         version: "0.14.0"
  #     - name: Setup MoonBit
  #       run: |
  #         curl -fsSL https://cli.moonbitlang.com/install/unix.sh | bash
  #         echo "$HOME/.moon/bin" >> $GITHUB_PATH
  #     - name: Build NTM Binary
  #       run: |
  #         cd ntm
  #         moon update
  #         moon build --target native
  #         cd ..
  #     - name: Prepare artifacts
  #       run: |
  #         mkdir -p dist
  #         cp zig-out/bin/ntm dist/ntm.exe
  #     - name: Upload artifacts
  #       uses: actions/upload-artifact@v4
  #       with:
  #         name: ntm-windows
  #         path: dist/*

  release:
    name: Create Release
    needs: [build-macos, build-linux]
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: artifacts/**/*